services:
  proxy:
    build:
      context: .
    command: [ "2000", "proxy" ]
    ports:
      - 2000:2000

  xml:
    build:
      context: .
    command: [ "3000", "xml" ]

  native:
    build:
      context: .
    command: [ "3001", "native" ]

  proto:
    build:
      context: .
    command: [ "3002", "proto" ]

